### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by AhmedAbdElaziz-dev** [axisj/react-multi-email#102]
this error happens when using it with react 17.0.0 
any idea how to solve it ?

**Comment by vmundhra** [comment]
I am too getting this error

**Comment by rajdeepkhandelwal** [comment]
I am to getting this error. how we can resolve this.
React version: 17.0.2

**Comment by monica-boga** [comment]
Can we please fix this for react 17+

**Comment by sblausten** [comment]
Same here

**Comment by shubhambatra** [comment]
any solution yet?? same error
`react.development.js:1630 Uncaught TypeError: Cannot read properties of null (reading 'useRef')
    at Object.useRef (react.development.js:1630:1)
    at ReactMultiEmail (ReactMultiEmail.js:40:1)
    at renderWithHooks (react-dom.development.js:16141:1)
    at mountIndeterminateComponent (react-dom.development.js:20838:1)
    at beginWork (react-dom.development.js:22342:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
    at performUnitOfWork (react-dom.development.js:26392:1)`

**Comment by garyfoo** [comment]
Hello,

Just want to mention here that I fixed this error after upgrading from React 17 -> 18!

**Comment by nandhu** [comment]
Use 0.5.3 version to fix this issue. 
```
npm i react-multi-email@0.5.3
```

**Comment by bikramnathdev** [comment]
And for styling, need to import css as 
import 'react-multi-email/style.css';

**Comment by 134130** [comment]
It looks resolved with https://github.com/axisj/react-multi-email/issues/116
